### ISSUE TITLE
panic: open api key is empty

### ISSUE THREAD

**Issue by Albertchamberlain** [ZBIGBEAR/openai-go#1]
您好，您这个项目非常不错,但是执行的预期可能与ReadME.md文件中的描述不符
ReadME中的配置方式二
cfg := &config.Config{
		OpenAI: config.OpenAI{
			OpenAPIKey: "YOUR_OPEN_API_KEY",
		},
	}

项目运行时首先执行的是openai.go中的init()，init()调用的New()传入nil，因此会导致key为空，panic: open api key is empty 
您在测试的时候应该是配置环境变量，所以这个功能并没有被测试到

改为如下即可
func init() {
	// 单例模式实例化内部默认openai实体
	Cfg := &config.Config{
		OpenAI: config.OpenAI{
			OpenAPIKey: "YOUR_OPEN_API_KEY",
		},
	}
	defaultOpenAIOnce.Do(func() {
		defaultOpenAI = New(Cfg)
	})
}
😀

**Comment by ZBIGBEAR** [comment]
你好，首先感谢你提的issues,我改了一下init方法，可以再看看。

目前openai的go sdk比较少，希望有一个比较好用的sdk。如果你有时间，诚邀你一起完善、推广，为开源做点贡献
